unepccc_app/urls.py
from django.urls import path
from . import views

app_name = 'unepccc_app'

urlpatterns = [
    path('', views.index_view, name='index-view'),
    path('projects/', views.project_list, name='project-view'),
    path('projects/<int:pk>', views.project_detail, name='project-details'),
    path('methodologies/', views.methodology_list, name='methodology-view'),
    path('methodologies/<int:pk>', views.methodology_detail,
         name='methodology-details'),
    path('analysis/', views.analysis, name='projects-by-region-view'),
    path('analysis/1/', views.projects_by_methodology, name='projects-by-methodology-view'),
    path('analysis/2/', views.credits_by_sector, name='credits-by-sector-view'),
    path('buyers/', views.buyer_list, name='buyers-view'),
    path('consultants/', views.consultant_list, name='consultants-view'),
]

htmx_urlpatterns = [
    path('select-sector/', views.select_sector, name="select-sector"),
    path('search-project/<int:pk>', views.search_project, name="search-project"),
]

urlpatterns += htmx_urlpatterns

unepccc_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('unepccc_app.urls')),
]

unepccc_app/models.py
import uuid
from django.db import models
from django.db.models.query import QuerySet
from django.db.models import Sum


class Region(models.Model):
    name = models.CharField(max_length=50, unique=True)

    @property
    def sub_regions(self) -> QuerySet:
        return Sub_region.objects.filter(region=self.id)

    @property
    def countries(self) -> QuerySet:
        return Country.objects.filter(sub_region__region=self.id)

    @property
    def project_count(self):
        return Project.objects.filter(country__sub_region__region=self.id).count()

    def __str__(self):
        return self.name


class Sub_region(models.Model):
    name = models.CharField(max_length=50, unique=True)
    region = models.ForeignKey(Region, on_delete=models.PROTECT)

    @property
    def countries(self) -> QuerySet:
        return Country.objects.filter(sub_region=self.id)

    def __str__(self):
        return self.name


class Country(models.Model):
    name = models.CharField(max_length=50, unique=True)
    sub_region = models.ForeignKey(Sub_region, on_delete=models.PROTECT)

    @property
    def project_count(self) -> QuerySet:
        return Project.objects.filter(country=self.id).count()

    class Meta:
        verbose_name_plural = 'countries'

    def __str__(self):
        return self.name


class Sector(models.Model):
    name = models.CharField(max_length=100)

    @property
    def methodologies(self) -> QuerySet:
        return Methodology.objects.filter(sector=self.id).annotate(credits=Sum('project__credit__credit'))

    @property
    def project_count(self):
        return Project.objects.filter(methodology__sector=self.id).count()

    def __str__(self):
        return self.name


class Methodology(models.Model):
    name = models.CharField(max_length=500)
    methodology_id = models.CharField(max_length=20)
    sector = models.ForeignKey(Sector, on_delete=models.PROTECT)
    description = models.TextField()

    @property
    def projects(self) -> QuerySet:
        return Project.objects.filter(methodology=self.id).annotate(credits=Sum('credit__credit'))

    @property
    def project_count(self) -> QuerySet:
        return Project.objects.filter(methodology=self.id).count()

    class Meta:
        verbose_name_plural = 'methodologies'

    def __str__(self):
        return self.methodology_id


class Organisation(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Buyer(models.Model):
    name = models.CharField(max_length=200)
    organisation = models.ForeignKey(Organisation, on_delete=models.PROTECT)
    country = models.ForeignKey(Country, on_delete=models.PROTECT)

    @property
    def project_count(self) -> QuerySet:
        return Project.objects.filter(buyer=self.id).count()

    def __str__(self):
        return self.name


class PDD_consultant(models.Model):
    name = models.CharField(max_length=200)
    organisation = models.ForeignKey(Organisation, on_delete=models.PROTECT)
    country = models.ForeignKey(Country, on_delete=models.PROTECT)

    @property
    def project_count(self) -> QuerySet:
        return Project.objects.filter(pdd_consultant=self.id).count()

    def __str__(self):
        return self.name


class Status(models.Model):
    name = models.CharField(max_length=80)

    @property
    def project_count(self) -> QuerySet:
        return Project.objects.filter(status=self.id).count()

    class Meta:
        verbose_name_plural = 'status'

    def __str__(self):
        return self.name


class Type(models.Model):
    name = models.CharField(max_length=100)

    @property
    def project_count(self) -> QuerySet:
        return Project.objects.filter(sub_type__type=self.id).count()

    def __str__(self):
        return self.name


class Sub_type(models.Model):
    name = models.CharField(max_length=100)
    type = models.ForeignKey(Type, on_delete=models.PROTECT)

    @property
    def project_count(self) -> QuerySet:
        return Project.objects.filter(sub_type=self.id).count()

    def __str__(self):
        return self.name


class Validator(models.Model):
    name = models.CharField(max_length=200)
    short_name = models.CharField(max_length=50)
    country = models.ForeignKey(Country, on_delete=models.PROTECT)

    @property
    def project_count(self) -> QuerySet:
        return Project.objects.filter(validator=self.id).count()

    def __str__(self):
        return self.short_name


class Project(models.Model):
    name = models.CharField(max_length=500)
    project_id = models.CharField(max_length=50)
    project_ref = models.CharField(max_length=20)
    idVal = models.UUIDField(default=uuid.uuid4, primary_key=False)
    methodology = models.ForeignKey(Methodology, on_delete=models.PROTECT)
    country = models.ForeignKey(Country, on_delete=models.PROTECT)
    status = models.ForeignKey(Status, on_delete=models.PROTECT)
    sub_type = models.ForeignKey(Sub_type, on_delete=models.PROTECT)
    buyer = models.ForeignKey(Buyer, on_delete=models.PROTECT)
    pdd_consultant = models.ForeignKey(
        PDD_consultant, on_delete=models.PROTECT)
    validator = models.ForeignKey(Validator, on_delete=models.PROTECT)
    expected_CERs = models.IntegerField(default=0)
    credit_start = models.DateField(auto_now_add=False, blank=True, null=True)

    def __str__(self):
        return self.project_id


class Credit(models.Model):
    credit = models.IntegerField()
    date = models.DateField(auto_now_add=False, blank=True)
    project = models.ForeignKey(Project, on_delete=models.PROTECT)

    def __int__(self):
        return self.credit

unepccc_app/forms.py
from django import forms


class ProjectForm(forms.Form):
    name = forms.CharField()

unepccc_app/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from django.db.models import Count, Sum

from bokeh.models import ColumnDataSource, HoverTool, Legend
from bokeh.models.tools import PanTool, ResetTool, SaveTool
from bokeh.embed import components
from bokeh.plotting import figure
from bokeh.resources import INLINE
from bokeh.palettes import Spectral5
from bokeh.transform import factor_cmap, dodge

from .filters import ProjectFilter
from .models import Project, Sector, Methodology, Region, Status, Credit, Buyer, PDD_consultant

from csp.decorators import csp_exempt


@csp_exempt
def index_view(request):
    return render(request, 'unepccc_app/index.html', {'message': 'index view'})


@csp_exempt
def project_list(request):
    project_filter = ProjectFilter(request.GET, Project.objects.all().annotate(
        credits=Sum('credit__credit')).order_by('name'))

    context = {
        'form': project_filter.form,
        'projects': project_filter.qs
    }

    if request.htmx:
        template_url = True
        message = "We can't find any projects that match your search."
        context = {
            'form': project_filter.form,
            'projects': project_filter.qs,
            'template_url': template_url,
            'message': message
        }
        return render(request, 'unepccc_app/partials/project_list.html', context)
    return render(request, 'unepccc_app/project.html', context)


@csp_exempt
def project_detail(request, pk):
    project = get_object_or_404(Project, pk=pk)
    credits = Credit.objects.filter(project=pk)
    credit_sum = Project.objects.annotate(
        total_credits=Sum('credit__credit')).get(pk=pk)
    total_credits = credit_sum.total_credits
    context = {'project': project, 'credits': credits,
               'total_credits': total_credits}
    return render(request, 'unepccc_app/project_detail.html', context)


@csp_exempt
def methodology_list(request):
    sectors = Sector.objects.all()
    context = {'sectors': sectors}
    return render(request, 'unepccc_app/methodology.html', context)


@csp_exempt
def methodology_detail(request, pk):
    methodology = get_object_or_404(Methodology, pk=pk)
    context = {'methodology': methodology}
    return render(request, 'unepccc_app/methodology_detail.html', context)


@csp_exempt
def buyer_list(request):
    buyers = Buyer.objects.all()
    context = {'buyers': buyers}
    return render(request, 'unepccc_app/buyers.html', context)


@csp_exempt
def consultant_list(request):
    consultants = PDD_consultant.objects.all()
    context = {'consultants': consultants}
    return render(request, 'unepccc_app/consultants.html', context)


# HTMX functions
@csp_exempt
def select_sector(request):
    sector = request.GET.get('sector')
    if sector == 'all':
        sectors = Sector.objects.all()
        context = {'sectors': sectors}
        return render(request, 'unepccc_app/partials/methodology_list.html', context)
    else:
        sector = Sector.objects.get(pk=sector)
        context = {'sector': sector}
        return render(request, 'unepccc_app/partials/methodology_list_selected.html', context)


@csp_exempt
def search_project(request, pk):
    search_text = request.POST.get('search')

    projects = Project.objects.filter(methodology=pk) & Project.objects.filter(
        Q(name__icontains=search_text) |
        Q(project_id__icontains=search_text) |
        Q(country__name__icontains=search_text) |
        Q(status__name__icontains=search_text)
    )

    context = {'projects': projects}
    if projects.count() == 0:
        message = "We can't find any projects that match your search."
        context = {
            'projects': projects,
            'message': message
        }
    return render(request, 'unepccc_app/partials/project_list.html', context)


@csp_exempt
def analysis(request):

    projects = Project.objects.all().values('country__sub_region__region__name').annotate(
        count=Count('country__sub_region__region__name')).order_by('count').reverse()

    region_names = [r['country__sub_region__region__name'] for r in projects]
    region_projects = [r['count'] for r in projects]

    data = {'region_names': region_names, 'region_projects': region_projects}
    cds = ColumnDataSource(data=data)

    fig = figure(x_range=region_names, y_range=(0, max(region_projects) + 1), height=450,
                 title=f'{"Number of projects by Region"}', tools=[SaveTool(), PanTool(), ResetTool()])

    fig.title.align = 'left'
    fig.title.text_font_size = '1.7em'
    fig.title.text_font_style = 'normal'
    fig.title.text_color = '#01465F'
    fig.border_fill_color = "whitesmoke"
    fig.min_border = 60
    fig.yaxis.axis_label = "Number of projects"
    fig.y_range.start = 0
    fig.toolbar.autohide = True
    fig.toolbar.logo = None
    fig.sizing_mode = "stretch_width"
    fig.axis.minor_tick_line_color = None

    tooltips = [
        ('Region', '@region_names'),
        ('Projects', '@region_projects')
    ]
    fig.vbar(source=cds, x='region_names',
             top='region_projects', width=0.5)

    fig.xgrid.grid_line_color = None
    fig.outline_line_color = None

    fig.add_tools(HoverTool(tooltips=tooltips))

    script, div = components(fig)

    context = {'resources': INLINE.render(), 'script': script,
               'div': div}

    if request.htmx:
        return render(request, 'unepccc_app/partials/bar_chart.html', context)
    return render(request, 'unepccc_app/analysis.html', context)


@csp_exempt
def projects_by_methodology(request):
    status_list = Status.objects.all()
    default_status = status_list.get(pk=1)
    status = request.GET.get('status', default_status)
    count = int(request.GET.get('count', 5))
    projects = Project.objects.filter(status=status).values('methodology__methodology_id').annotate(
        count=Count('methodology')).order_by('count').reverse()[:count]

    methodologies = [r['methodology__methodology_id'] for r in projects]
    projects = [r['count'] for r in projects]

    data = {'methodologies': methodologies, 'projects': projects}
    cds = ColumnDataSource(data=data)

    method_cmap = factor_cmap(
        'methodologies', palette=Spectral5, factors=methodologies)
    fig = figure(x_range=methodologies, y_range=(0, max(projects) + 1),
                 height=450, title=f'{"Number of projects by Methodology and Status"}')
    fig.title.align = 'left'
    fig.title.text_font_size = '1.7em'
    fig.title.text_font_style = 'normal'
    fig.title.text_color = '#01465F'
    fig.border_fill_color = "whitesmoke"
    fig.min_border = 60
    fig.yaxis.axis_label = "Number of projects"
    fig.y_range.start = 0
    fig.toolbar.autohide = True
    fig.toolbar.logo = None
    fig.sizing_mode = "stretch_width"
    # fig.axis.minor_tick_in = -3
    # fig.axis.minor_tick_out = 6
    fig.axis.minor_tick_line_color = None

    tooltips = [
        ('Methodology', '@methodologies'),
        ('Projects', '@projects')
    ]
    fig.vbar(source=cds, x='methodologies',
             top='projects', width=0.5, line_color=method_cmap, fill_color=method_cmap)

    fig.xgrid.grid_line_color = None
    fig.outline_line_color = None

    fig.add_tools(HoverTool(tooltips=tooltips))

    script, div = components(fig)
    context = {'resources': INLINE.render(), 'script': script,
               'div': div, 'status': status_list, 'status_selected': status, 'count': count}
    if request.htmx:
        return render(request, 'unepccc_app/partials/bar_chart.html', context)
    return render(request, 'unepccc_app/projects_by_methodology.html', context)


@csp_exempt
def credits_by_sector(request):
    projects = Project.objects.all().values('methodology__sector__name').annotate(
        count=Count('methodology__sector__name'), credits_2025=Sum('expected_CERs'), total_issuances=Sum('credit__credit')).order_by('count').reverse()[:3]

    sectors = [s['methodology__sector__name'] for s in projects]
    credits_2025 = [c['credits_2025'] for c in projects]
    total_issuances = [c['total_issuances'] for c in projects]

    data = {'sectors': sectors,
            'CERs 2025': credits_2025,
            'Total issuance': total_issuances}

    source = ColumnDataSource(data=data)

    fig = figure(x_range=sectors, height=450, title="CERs by Sector")

    v1 = fig.vbar(x=dodge('sectors', -0.25, range=fig.x_range),
                  top='CERs 2025', source=source, width=0.2, color="#0072B2")
    v2 = fig.vbar(x=dodge('sectors', 0.0, range=fig.x_range),
                  top='Total issuance', source=source, width=0.2, color="#E69F00")

    fig.title.align = 'left'
    fig.title.text_font_size = '1.7em'
    fig.title.text_font_style = 'normal'
    fig.title.text_color = '#01465F'
    fig.border_fill_color = "whitesmoke"
    fig.min_border = 60
    fig.y_range.start = 0
    fig.x_range.range_padding = 0.1
    fig.xgrid.grid_line_color = None
    # fig.axis.minor_tick_line_color = None
    fig.outline_line_color = None
    fig.sizing_mode = "stretch_width"
    fig.toolbar.autohide = True
    fig.toolbar.logo = None

    legend = Legend(items=[
        ("CERs 2025",   [v1]),
        ("Total issuance",   [v2]),
    ], location="center", orientation="horizontal")

    fig.add_layout(legend, 'below')

    script, div = components(fig)
    context = {'resources': INLINE.render(), 'script': script, 'div': div}

    return render(request, 'unepccc_app/credits_by_sector.html', context)

unepccc_app/templates/unepccc_app/analysis.html
{% extends 'unepccc_app/base.html' %}
{% block title %} Analysis {% endblock title %}
{% block content %}
<div class="container mt-5 pt-4">
    <h1>Analysis</h1>
    <div class="row my-5">
        <div class="col-lg-4">
            {% include 'unepccc_app/partials/analysis_menu.html' %}
        </div>
        <div class="col-lg-8 plot-wrapper">
            <div id="barchart">{% include 'unepccc_app/partials/bar_chart.html' %}</div>
        </div>
    </div>
</div>
{% endblock content %}

unepccc_app/templates/unepccc_app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta name="description" content="unepccc_app" />
    <meta name="keywords" content="unepccc_app" />
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!--Google Fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700&display=swap"
        rel="stylesheet" />
    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <!--Bootstrap JS-->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous">
    </script>
    <!--HTMX-->
    <script src="https://unpkg.com/htmx.org@1.8.4"></script>
    <!--Bokeh-->
    {{ resources | safe }}
    {% load static %}
    {% load extra_tags %}
    <!--CSS-->
    <link rel="stylesheet" href="{% static 'unepccc_app/style.css' %}" />
    <!-- Link to page favicon.ico to display in location Bar-->
    <link rel="icon" href="{% static 'unepccc_app/images/favicon.ico' %}" />
    <title>Article 6 | Pipeline -
        {% block title %}
        Home
        {% endblock title %}
    </title>
</head>

<body>
    <header>
        <div class="header-top container d-flex justify-content-between my-4">
            <div class="col-6 p-0">
                <a class="logo-home" href="{% url 'unepccc_app:index-view' %}">Article 6 Pipeline</a>
            </div>
            <a class="col-6 d-flex justify-content-end p-0" href="#">
                <img class="logo-unepccc" src="{% static 'unepccc_app/images/unepccc-logo.svg' %}" />
            </a>
        </div>
        <nav>
            <ul class="container list-unstyled d-md-flex py-3 mb-0">
                <li class=" {% activate_on 'project-view' %} ">
                    <a class="nav-li" href="{% url 'unepccc_app:project-view' %}">Projects</a>
                </li>
                <li class=" {% activate_on 'methodology-view' %} ">
                    <a class="nav-li" href="{% url 'unepccc_app:methodology-view' %}">Methodologies</a>
                </li>
                <li
                    class=" {% activate_on 'projects-by-region-view' %} {% activate_on 'projects-by-methodology-view' %} {% activate_on 'credits-by-sector-view' %} ">
                    <a class="nav-li" href="{% url 'unepccc_app:projects-by-region-view' %}">Analysis</a>
                </li>
                <li class=" {% activate_on 'buyers-view' %} ">
                    <a class="nav-li" href="{% url 'unepccc_app:buyers-view' %}">Buyers</a>
                </li>
                <li class=" {% activate_on 'consultants-view' %} ">
                    <a class="nav-li" href="{% url 'unepccc_app:consultants-view' %}">PDD Consultants</a>
                </li>
            </ul>
        </nav>
    </header>
    <main>
        {% block content %}
        {% endblock content %}
    </main>
    <footer class="footer-wrapper">
        <div class="container p-0 py-4">
            <div class="col-12 row py-5 mx-0 px-0">
                <div class="col-lg-7 mb-4 mb-lg-0">
                    <a class="logo-home" href="{% url 'unepccc_app:index-view' %}">Article 6 Pipeline</a>
                    <p class="mt-3 mb-5">
                        {% lorem %}
                    </p>
                    <a href="#">
                        <img class="logo-unepccc" src="{% static 'unepccc_app/images/unepccc-logo-white.svg' %}" />
                    </a>
                </div>
                <div class="col-lg-5">
                    <div class="row justify-content-lg-end mt-3">
                        <ul class="list-unstyled ml-3 ml-lg-0">
                            <li class="mb-2">
                                <a class="footer-li" href="{% url 'unepccc_app:project-view' %}">Projects</a>
                            </li>
                            <li class="mb-2">
                                <a class="footer-li" href="{% url 'unepccc_app:methodology-view' %}">Methodologies</a>
                            </li>
                            <li class="mb-2">
                                <a class="footer-li" href="{% url 'unepccc_app:projects-by-region-view' %}">Analysis</a>
                            </li>
                            <li class="mb-2">
                                <a class="footer-li" href="{% url 'unepccc_app:buyers-view' %}">Buyers</a>
                            </li>
                            <li class="mb-2">
                                <a class="footer-li" href="{% url 'unepccc_app:consultants-view' %}">PDD Consultants</a>
                            </li>
                        </ul>
                        <ul class="list-unstyled ml-5 pl-5">
                            <li class="mb-2">
                                <a class="footer-li" href="">About</a>
                            </li>
                            <li class="mb-2">
                                <a class="footer-li" href="">Resources</a>
                            </li>
                            <li class="mb-2">
                                <a class="footer-li" href="">Contact</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--JavaScript-->
    <script src="{% static 'unepccc_app/script.js' %}"></script>
    <!--Bokeh-->
    <script src="https://cdn.bokeh.org/bokeh/release/bokeh-3.0.0.min.js" crossorigin="anonymous"></script>
</body>

</html>

unepccc_app/templates/unepccc_app/index.html
{% extends 'unepccc_app/base.html' %}
{% load static %}
{% block content %}
<div class="hero-banner">
    <div class="container hero-text d-flex align-items-center">
        <h1 class="col-md-6 pl-0 pr-lg-5 hero-heading">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis aute irure dolor in reprehenderit in voluptate
            velit.
        </h1>
    </div>
    <div class="hero-image">
        <img src="{% static 'unepccc_app/images/splash-image.jpg' %}" />
    </div>
</div>
<div class="cta-wrapper container my-lg-5 py-4 py-lg-5">
    <div class="cta-row my-5">
        <a class="cta-a" href="{% url 'unepccc_app:project-view' %}">
            <div class="cta-item p-4">
                <img class="mb-3" src="{% static 'unepccc_app/images/projects-icon.svg' %}" />
                <h5 class="mb-3">Projects</h5>
                <p class="mb-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet,
                    consectetur
                    adipiscing elit.</p>
                <button class="cta-btn mb-3">Read more</button>
            </div>
        </a>
        <a class="cta-a" href="{% url 'unepccc_app:methodology-view' %}">
            <div class="cta-item p-4">
                <img class="mb-3" src="{% static 'unepccc_app/images/methodology-icon.svg' %}" />
                <h5 class="mb-3">Methodologies</h5>
                <p class="mb-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet,
                    consectetur
                    adipiscing elit.</p>
                <button class="cta-btn mb-3">Read more</button>
            </div>
        </a>
        <a class="cta-a" href="{% url 'unepccc_app:projects-by-region-view' %}">
            <div class="cta-item p-4">
                <img class="mb-3" src="{% static 'unepccc_app/images/analysis-icon.svg' %}" />
                <h5 class="mb-3">Analysis</h5>
                <p class="mb-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet,
                    consectetur
                    adipiscing elit.</p>
                <button class="cta-btn mb-3">Read more</button>
            </div>
        </a>
    </div>
</div>
<div class="about-wrapper mt-lg-5 py-5">
    <div class="container py-5">
        <div class="row">
            <div class="col-lg-6">
                <h4 class="home-about-header pr-lg-5 mb-4"><strong>Lorem ipsum</strong> dolor sit amet, consectetur
                    adipisicing elit,
                    sed do eiusmod tempor
                    incididunt ut labore et
                    dolore magna aliqua. </h4>
            </div>
            <div class="col-lg-6">
                <p>{% lorem %}</p>
                <p>{% lorem %}</p>
                <p>{% lorem %}</p>
                <hr class="mt-5">
                <div class="contact-info row align-items-center my-4 py-2">
                    <div class="contact-img col-4 col-md-3">
                        <img class="rounded-circle"
                            src="https://unepccc.org/wp-content/uploads/2018/10/karen-cropped-300x300.jpg">
                    </div>
                    <div class="info col-8 col-md-9">
                        <p class="mb-1">Karen Holm Olsen</p>
                        <p class="mb-1">Senior Researcher</p>
                        <p class="mb-1">Email: <a class="contact-a"
                                href="mailto:karen.olsen@un.org">karen.olsen@un.org</a></p>
                        <p class="mb-1">Tel.: <a class="contact-a" href="tel:+45 4533 5295">+45 4533 5295</a></p>
                    </div>
                </div>
                <hr>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

unepccc_app/templates/unepccc_app/methodology.html
{% extends 'unepccc_app/base.html' %}
{% block title %}Methodologies{% endblock title %}
{% block content %}
<div class="container mt-5 pt-4 mb-10">
    <div class="section-header col-lg-8 p-0 mb-5">
        <h1 class="mb-3">Approved Methodologies</h1>
        {% lorem %}
    </div>
    <div class="my-4">
        <select class="custom-select mb-4" name="sector" hx-get="{% url 'unepccc_app:select-sector' %}"
            hx-trigger="change" hx-target="#sector-wrapper">
            <option selected value="all">Sectors</option>
            {% for sector in sectors %}
            <option value="{{ sector.id }}"> {{ sector.name }}</option>
            {% endfor %}
        </select>
    </div>
    <div id="sector-wrapper">
        {% if sector %}
        {% include 'unepccc_app/partials/methodology_list_selected.html' %}
        {% elif sectors %}
        {% include 'unepccc_app/partials/methodology_list.html' %}
        {% endif %}
    </div>
</div>
{% endblock content %}

unepccc_app/templates/unepccc_app/project.html
{% extends 'unepccc_app/base.html' %}
{% load static %}
{% block title %}Projects{% endblock title %}
{% block content %}
<div class="container mt-5 pt-4 mb-10">
    <div class="section-header col-lg-8 p-0 mb-5">
        <h1 class="mb-3">Projects</h1>
        {% lorem %}
    </div>
    <div class="row pt-5">
        <div class="col-lg-4 pr-lg-5">
            <div class="filters-header mb-3 d-flex align-items-center">
                <p class="m-0 mx-2">Filters</p>
                <img class="filters-icon" src="{% static 'unepccc_app/images/filters-white.svg' %}" />
            </div>
            <form class="filters-form" hx-get="{% url 'unepccc_app:project-view' %}" hx-target="#project-wrapper">
                {{ form.as_p}}
                <button class="project-btn-submit w-100 mt-3">Submit</button>
            </form>
            <div class="my-5">
                <a class="tx-btn clear-filter-btn d-none" href="{% url 'unepccc_app:project-view' %}">Clear filters</a>
            </div>
        </div>
        <div class="col-lg-8">
            <div class="project-wrapper" id="project-wrapper">
                {% include 'unepccc_app/partials/project_list.html' %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}